
project_id = "wkmyvthtyjcdzhzvfyji"

[api]
enabled = true
custom_api_port = 54321
insecure_port = 54325
port = 54324
uri = "http://127.0.0.1:54325"

[auth]
require_emails_on_signup = false

[compiler]
watch = true

[functions.ask-assistant]
verify_jwt = true
import_map = "import_map.json"

[functions.generate-insights]
verify_jwt = true
import_map = "import_map.json"

[functions.sync-user-data]
verify_jwt = true
import_map = "import_map.json"

[functions.track-performance]
verify_jwt = false
import_map = "import_map.json"

