
project_id = "wkmyvthtyjcdzhzvfyji"

[functions.get-practice-progress]
verify_jwt = true

[functions.track-practice-completion]
verify_jwt = true

[functions.handle-portal-interaction]
verify_jwt = true
