
name: TypeScript Type Check

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Validate configuration
        run: |
          # Create temporary validation script
          echo "
          import { validateAppConfig } from './src/utils/config/configValidator';
          
          // Run validation
          const isValid = validateAppConfig();
          
          // Exit with appropriate code
          process.exit(isValid ? 0 : 1);
          " > validate-config.mjs
          
          # Set dummy environment variables for testing
          export VITE_SUPABASE_URL="https://test.supabase.co"
          export VITE_SUPABASE_ANON_KEY="test-key"
          
          # Run validation script
          node validate-config.mjs || (echo "Configuration validation failed" && exit 1)

      - name: TypeScript type check
        run: npx tsc --noEmit

      - name: ESLint check
        run: npx eslint . --ext .ts,.tsx

      - name: Find unused exports
        run: npx ts-unused-exports tsconfig.json --excludePathsFromReport="node_modules,dist,build"

      - name: Circular dependency check
        run: npx madge --circular --extensions ts,tsx src/

      - name: Bundle size analysis
        run: |
          npm run build
          npx source-map-explorer 'dist/**/*.js' --html bundle-analysis.html

      - name: Upload bundle analysis
        uses: actions/upload-artifact@v4
        with:
          name: bundle-analysis
          path: bundle-analysis.html
